<script>
    $(document).ready(function(){
        $('.owl-carousel').owlCarousel({
            margin:10,
            autoWidth:true,
            items:1
        });
    });
</script>
</body>
</html>